#!/usr/bin/php
<?php

function os() {
   return (stripos(PHP_OS, "WIN") === 0)? "DOS" : "UNIX";
}

$os = os();
if($os == 'WIN') {
    system("cls");
}else{
    system("clear");
}

echo "
            |  _ \(_) |__   __ _ _ __ ___   __ _ _ __  |  ___/ ___| 
            | |_) | | '_ \ / _` | '_ ` _ \ / _` | '__| | |_  \___ \ 
            |  _ <| | |_) | (_| | | | | | | (_| | |    |  _|  ___) |
            |_| \_\_|_.__/ \__,_|_| |_| |_|\__,_|_|    |_|   |____/ 

                    \_|_)                             | | 
                      |     __,   ,_    __,        _  | | 
                     _|    /  |  /  |  /  |  |  |_|/  |/  
                    (/\___/\_/|_/   |_/\_/|_/ \/  |__/|__/
                              Criado com figlet";

    echo "\n\n\t================== Utilitários com PHP-CLI ====================\n\n";
    echo "\t- Instalar laravel [8] [7] [6] [58]\n";
    echo "\t- Implementar [a]utenticação no laravel 8\n";
    echo "\t- Limpar o [c]ache do laravel atual\n";
    echo "\t- Backup de [b]anco mysql\n";
    echo "\t- Sair [s]\n\n";
    echo "\t===============================================================\n\n";
    $ret = readline("Digite a letra da opção acima entre concletes. Ex [8] => ");

if ($ret === "8"){ 
    echo "\nInstalar laravel 8 em qual pasta?\n";
    $pasta = fgets(STDIN);
    system("composer create-project --prefer-dist laravel/laravel:^8.0 $pasta");
    echo "\nAguarde a instalação ...";
}elseif ($ret === "7"){
    echo "\nInstalar laravel 7 em qual pasta?\n";
    $pasta = fgets(STDIN);
    system("composer create-project --prefer-dist laravel/laravel:^7.0 $pasta");
    echo "\nAguarde a instalação ...";
}elseif ($ret === "6"){
    echo "\nInstalar laravel 6 em qual pasta?\n";
    $pasta = fgets(STDIN);
    system("composer create-project --prefer-dist laravel/laravel:^6.0 $pasta");
    echo "\nAguarde a instalação ...";
}elseif ($ret === "58"){
    echo "Instalar laravel 5.8 em qual pasta?\n";
    $pasta = fgets(STDIN);
    system("composer create-project --prefer-dist laravel/laravel:^5.8 $pasta");
    echo "\nAguarde a instalação ...";
}elseif ($ret === "a"){
    auth8();
}elseif ($ret === "c"){
    chearCache();
}elseif ($ret === "b"){
    backupDb();
}elseif ($ret === "s"){
    if($os == 'WIN') {
        system("cls");
    }else{
        system("clear");
    }
    exit(0);
}

function auth8(){
    echo 'Aguarde a implementação da autenticação no Laravel 8 na pasta atual...';
    echo PHP_EOL;
    exec('composer require laravel/jetstream');
    echo PHP_EOL;
    echo "Digite sua escolha: livewire/inertia";
    $front = fgets(STDIN);
    exec('php artisan jetstream:install '.$front);
    exec('npm install && npm run dev');
    exec('npm audit fix');
    echo PHP_EOL;
    echo 'Autenticação com '.$front.' implementada no Laravel 8';
    echo PHP_EOL;
}

function clearCache(){
    system('php artisan view:clear');
    system('php artisan cache:clear');
    system('php artisan route:clear');
    system('php artisan route:cache');
    system('php artisan config:cache');
    system('php artisan optimize');
    system('composer du');
}

function backupDb(){
    echo 'O backup será feito na pasta atual: bk.sql';
    echo PHP_EOL;        
    $filename = 'backup-'.date('Y-m-d_H-i').'.sql';
    echo "Nome do banco de dados?\n";
    $db = trim(fgets(STDIN));
    echo "Nome do usuário?\n";
    $user = trim(fgets(STDIN));
    echo "Senha?\n";
    $pass = trim(fgets(STDIN));

    try {
        system("mysqldump -u $user -p$pass $db > $filename");
    } catch (\Exception $e) {
        echo 'mysqldump-php error: ' . $e->getMessage();
    }
}

